- name: Generate client certificate key
  openssl_privatekey:
    path: "{{ client_key }}"
    size: 4096
    state: present
    backup: yes
    
- name: Generate client certificate signing request
  openssl_csr:
    path: "{{ client_csr }}"
    privatekey_path: "{{ client_key }}"
    common_name: "{{ client_name }}"
    country_name: "{{ country }}"

- name: Generate client Certificate
  openssl_certificate:
    path: "{{ client_crt }}"
    #privatekey_path: "{{ client_key }}"
    csr_path: "{{ client_csr }}"
    ownca_path: "{{ ca_crt }}"
    ownca_privatekey_path: "{{ ca_key }}"
    provider: ownca 
