- name: Install epel repository
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: Install openssl package
  yum:
    name: openssl
    state: present
    update_cache: yes

- name: Install openvpn package
  yum:
    name: openvpn
    state: present
    update_cache: yes

